version: '3.8'

services:
  # Mem0 Web UI 服务
  mem0-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mem0-webui
    ports:
      - "8503:8503"
    environment:
      - STREAMLIT_SERVER_PORT=8503
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - POSTGRES_HOST=mem0-postgres
      - POSTGRES_DB=mem0
      - POSTGRES_USER=mem0
      - POSTGRES_PASSWORD=mem0_secure_password_2024
      - POSTGRES_PORT=5432
      - MEM0_API_URL=http://mem0-api:8000
      - MEM0_API_KEY=${MEM0_API_KEY:-local_api_key}
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      # 挂载源码，支持实时调试
      - .:/app
    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8503/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  webui_data:
    driver: local

networks:
  default:
    external: true
    name: mem0-unified-network
