version: '3.8'

services:
  gemini-balance:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gemini-balance
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      # 确保MySQL配置正确传递
      - DATABASE_TYPE=mysql
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=gemini
      - MYSQL_PASSWORD=change_me
      - MYSQL_DATABASE=default_db
    volumes:
      - ./data:/app/data
      # 挂载源码，支持实时开发调试
      - .:/app
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mem0-unified-network
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; exit(0) if requests.get('http://localhost:8000/health').status_code == 200 else exit(1)\""]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

  mysql:
    image: mysql:8.0
    container_name: gemini-balance-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: default_db
      MYSQL_USER: gemini
      MYSQL_PASSWORD: change_me
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mem0-unified-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  mem0-unified-network:
    external: true

volumes:
  mysql_data:
    driver: local
