# Mem0 配置文件 - Gemini Balance模式 (临时禁用图数据库)

llm:
  provider: openai  # 使用OpenAI兼容接口连接Gemini Balance（已修复Function Calling）
  config:
    model: gemini-2.0-flash-exp
    temperature: 0.4  # 平衡准确性和泛化能力，支持语义推理和灵活理解
    max_tokens: 8000

embedder:
  provider: openai  # 使用OpenAI兼容接口连接Gemini Balance
  config:
    model: gemini-embedding-001  # 使用Gemini专用embedding模型，语义理解更好

vector_store:
  provider: qdrant
  config:
    collection_name: mem0_collection_v3  # 升级到新collection，支持3072维度
    host: mem0-qdrant
    port: 6333
    embedding_model_dims: 3072  # gemini-embedding-001 最佳性能维度

# 临时注释掉图数据库配置，因为Function Calling有兼容性问题
# graph_store:
#   provider: neo4j
#   config:
#     url: bolt://mem0-neo4j:7687
#     username: neo4j
#     password: password
