# Mem0 配置文件 - Gemini Balance模式
version: "v1.1"

llm:
  provider: openai  # 使用OpenAI兼容接口连接Gemini Balance
  config:
    model: gemini-2.0-flash-exp
    temperature: 0.3
    max_tokens: 8000

embedder:
  provider: openai  # 使用OpenAI兼容接口连接Gemini Balance
  config:
    model: text-embedding-004

vector_store:
  provider: qdrant
  config:
    collection_name: mem0_collection
    host: mem0-qdrant
    port: 6333
    embedding_model_dims: 768  # Gemini embedding dimensions
