# Mem0 配置文件 - 生产环境
version: "v1.1"

llm:
  provider: openai
  config:
    model: gemini-2.0-flash-exp
    temperature: 0.3
    max_tokens: 8000

embedder:
  provider: openai
  config:
    model: text-embedding-004

vector_store:
  provider: qdrant
  config:
    collection_name: mem0_collection
    host: mem0-qdrant
    port: 6333
    embedding_model_dims: 768
