# Mem0 配置文件 - OpenAI模式
version: "v1.1"

llm:
  provider: openai
  config:
    model: gpt-4o-mini
    temperature: 0.3
    max_tokens: 8000

embedder:
  provider: openai
  config:
    model: text-embedding-3-small

vector_store:
  provider: qdrant
  config:
    collection_name: mem0_collection
    host: mem0-qdrant
    port: 6333
    embedding_model_dims: 1536  # OpenAI embedding dimensions
